// This file is automatically generated and contains assets from telosTestnet.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0xF9485b3fffd191e28a089C21cD745cc228a181E3');
export const USDT_ADDRESS = Address.fromString('0x39D33701581EE17DfF7dBeEcCC35210aEE7B0417');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xF9485b3fffd191e28a089C21cD745cc228a181E3'), // USDC
    Address.fromString('0x39D33701581EE17DfF7dBeEcCC35210aEE7B0417'), // USDT
  ],
  pricingAssets: [
    Address.fromString('0xF5Dd4A1fCE57D9aCd7a4fEF03709402014b56813'), // WTLOs
    Address.fromString('0x4446664638E7cF5222c58907248cA3D8EE40b405'), // SYMM
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
