// This file is automatically generated and contains assets from meter.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0xd86e243fc0007e6226b07c9a50c9d70d78299eb5');
export const USDT_ADDRESS = Address.fromString('0x5fa41671c48e3c951afc30816947126ccc8c162e');
export const suUSD_ADDRESS = Address.fromString('0x8bf591eae535f93a242d5a954d3cde648b48a5a8');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xd86e243fc0007e6226b07c9a50c9d70d78299eb5'), // USDC
    Address.fromString('0x5fa41671c48e3c951afc30816947126ccc8c162e'), // USDT
    Address.fromString('0x8bf591eae535f93a242d5a954d3cde648b48a5a8'), // suUSD
    Address.fromString('0x1ff97abe4c5a4b7ff90949b637e71626bef0dcee'), // USDT-USDC-suUSD
  ],
  pricingAssets: [
    Address.fromString('0x228ebbee999c6a7ad74a6130e81b12f9fe237ba3'), // MTRG
    Address.fromString('0xe2de616fbd8cb9180b26fcfb1b761a232fe56717'), // wstMTRG
    Address.fromString('0x160361ce13ec33c993b5cca8f62b6864943eb083'), // MTR
    Address.fromString('0x2077a828fd58025655335a8756dbcfeb7e5bec46'), // MTRG-wstMTRG
  ],
  fxAssets: [],
  fxAggregators: [],
};
